### ISSUE TITLE
订阅号不能获取订阅的内容

### ISSUE THREAD

**Issue by DONGhuahao** [Kimentanm/aptv#4]

**Comment by Kimentanm** [comment]
请问用的是什么订阅？是内网的还是公网的？如果是公网的可以把链接贴给我试试吗？

**Comment by DONGhuahao** [comment]
https://img.whalenas.com:283/file/iptv.m3u

**Comment by Kimentanm** [comment]
这就是我发的那个测试地址啊，这个地址是可以访问的，你检查一下当前的网络，切换一下网络试试，或者是在浏览器里输一下这个地址看看是不是正常的---- 回复的原邮件 ***@***.***>发送日期2022年04月22日 18:19 ***@***.***> ***@***.******@***.***>主题Re: [Kimentanm/aptv] 订阅号不能获取订阅的内容 (Issue #4)
https://img.whalenas.com:283/file/iptv.m3u

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Kimentanm/aptv/issues/4#issuecomment-1106339558",
"url": "https://github.com/Kimentanm/aptv/issues/4#issuecomment-1106339558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gee1k** [comment]
你提供的这个测试地址中的浙江卫视能看到预览图但是无法加载视频，拿到电脑上用 IINA 测试正常播放

**Comment by Kimentanm** [comment]
> 你提供的这个测试地址中的浙江卫视能看到预览图但是无法加载视频，拿到电脑上用 IINA 测试正常播放

感谢反馈，我来检查一下

**Comment by lululubo** [comment]
期待本地配置功能。
还有可不可以实现后台小窗口模式呢？
感谢作者大大
